[package]
name = "director-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for the Director rendering engine"
license = "MIT"

[dependencies]
director-core = { path = "../director-core" }
rhai = "1.23.6"

[[bin]]
name = "director-engine"
path = "src/main.rs"
