[package]
name = "director-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
director-core = { path = "../director-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
